(lang dune 3.0)

(name ona-env-port-forward)

(generate_opam_files true)

(package
 (name ona-env-port-forward)
 (synopsis "Port forwarding tool for Gitpod environments with auto-reconnect")
 (depends
  (ocaml (>= 5.1))
  (yojson (>= 2.0))
  (minttea (>= 0.0.2))
  (spices (>= 0.0.2))))
